name: Delete Package 2
on:
  push:
    branches:    
      - 'main'
jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions 2
        #run: |
        #  echo 'Starting retrieving versions of package'
        #  curl -s -H "Accept:application/vnd.github.v3+json" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/rodrigolfaria/packages/container/test-actions/versions -o /tmp/response.json
        #  packagesId=`cat /tmp/response.json | jq '.[] | .id'`
        #  echo "packagesId: ${packagesId}"
        uses: snok/container-retention-policy@v1.4.2
        with:
          image-names: test-actions
          cut-off: one minute ago UTC
          timestamp-to-use: created_at
          # keep-at-least: 10
          #filter-tags: '23.0.0-r31ccfe7-202208101110'
          filter-tags: '24.0.0'
          account-type: personal
          #token: ${{ secrets.MY_GITHUB_PAT2 }}
          token: ${{ secrets.GITHUB_TOKEN }}
