name: Delete Package 2
on:
  push:
    branches:    
      - 'main'
jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions 2
        uses: snok/container-retention-policy@v1
        with:
          image-names: test-actions
          cut-off: one minute ago UTC
          timestamp-to-use: updated_at
          #keep-at-least: 10
          filter-tags: '24.0.0-r31ccfe7-20220810111*'
          account-type: personal
          token: ${{ secrets.MY_GITHUB_PAT2 }}
